# Generated by Django 5.2.7 on 2025-10-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_adminservice_providerservice"),
    ]

    operations = [
        migrations.AddField(
            model_name="providerservice",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
