# Generated by Django 5.2.7 on 2025-10-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_providerservice_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="serviceprovider",
            name="service_type",
        ),
        migrations.AlterField(
            model_name="providerservice",
            name="experience",
            field=models.CharField(
                choices=[
                    ("0-1", "0-1 years"),
                    ("2-3", "2-3 years"),
                    ("4-5", "4-5 years"),
                    ("6-10", "6-10 years"),
                    ("10+", "Above 10 years"),
                ],
                max_length=10,
            ),
        ),
    ]
