# Generated by Django 5.2.7 on 2025-10-22 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_serviceprovider_service_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="providerservice",
            name="name",
        ),
        migrations.RemoveField(
            model_name="providerservice",
            name="profile_pic",
        ),
    ]
