# Generated by Django 5.2.7 on 2025-10-22 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
        ("users", "0005_remove_providerservice_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="providerservice",
            name="service_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.service"
            ),
        ),
    ]
