# Generated by Django 5.2.7 on 2025-10-23 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_providerservice_service_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="serviceprovider",
            name="phone",
        ),
    ]
