# Generated by Django 5.2.7 on 2025-10-27 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_booking_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderEarning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_earnings",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "provider",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.serviceprovider",
                    ),
                ),
            ],
        ),
    ]
